# Generated by Django 4.2.6 on 2023-10-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage_visionmission_carouselimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_text',
        ),
    ]
