# Generated by Django 4.2.6 on 2023-10-31 18:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0008_productsafetydatasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('images', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
