# Generated by Django 4.2.6 on 2023-10-31 18:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_imagespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='images',
            field=wagtail.fields.StreamField([('name', wagtail.blocks.RichTextBlock()), ('designation', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
