# Generated by Django 4.2.6 on 2023-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_productsafetydatasheet_menu_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSafetyDataSheet',
        ),
    ]
