# Generated by Django 4.2.6 on 2023-11-01 19:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0014_delete_productsafetydatasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyDataSheet',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_field', wagtail.fields.StreamField([('is_file', wagtail.blocks.BooleanBlock(help_text='Check to enable feature', required=False)), ('file', wagtail.documents.blocks.DocumentChooserBlock(required=False))], blank=True, use_json_field=True)),
                ('parent', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.safetydatasheet')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
