# Generated by Django 4.2.6 on 2023-11-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_productspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetydatasheet',
            name='parent',
        ),
    ]
