# Generated by Django 4.2.6 on 2023-11-01 19:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_safetydatasheet_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetydatasheet',
            name='parent',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.safetydatasheet'),
        ),
    ]
