# Generated by Django 4.2.6 on 2023-11-01 19:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_safetydatasheet_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetydatasheet',
            name='parent',
        ),
        migrations.AddField(
            model_name='safetydatasheet',
            name='parent',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='children', to='home.safetydatasheet'),
        ),
    ]
