# Generated by Django 4.2.6 on 2023-11-01 20:41

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_secondmenu_remove_firstmenu_menu_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmenu',
            name='parent',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_children', to='home.productspecification'),
        ),
    ]
