# Generated by Django 4.2.6 on 2023-11-01 20:52

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_firstmenu_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmenu',
            name='parent',
        ),
        migrations.AddField(
            model_name='firstmenu',
            name='specification',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.productspecification'),
        ),
    ]
