# Generated by Django 4.2.6 on 2023-11-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_firstmenu_parent_firstmenu_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='enable_feature',
            new_name='is_file',
        ),
    ]
