# Generated by Django 4.2.6 on 2023-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_productspecification_is_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='is_file',
            field=models.BooleanField(default=False, help_text='Check to enable the feature'),
        ),
    ]
