# Generated by Django 4.2.6 on 2023-11-01 21:01

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_productspecification_is_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondmenu',
            name='specification',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.firstmenu'),
        ),
    ]
