# Generated by Django 4.2.6 on 2023-11-01 21:42

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0029_rename_enable_feature_firstmenu_is_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondMenu',
            new_name='SpecificationFirstMenu',
        ),
        migrations.RenameModel(
            old_name='FirstMenu',
            new_name='SpecificationSecondMenu',
        ),
        migrations.AlterField(
            model_name='specificationfirstmenu',
            name='specification',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.productspecification'),
        ),
    ]
