# Generated by Django 4.2.6 on 2023-11-01 21:46

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_secondmenu_specificationfirstmenu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationfirstmenu',
            old_name='specification',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='specificationsecondmenu',
            name='specification',
        ),
        migrations.AddField(
            model_name='specificationsecondmenu',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.specificationfirstmenu'),
        ),
    ]
