# Generated by Django 4.2.6 on 2023-11-01 21:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0031_rename_specification_specificationfirstmenu_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheetFirstMenu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('file_upload', wagtail.fields.StreamField([('file', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload a file', required=False))], blank=True, null=True, use_json_field=True)),
                ('is_file', models.BooleanField(default=False, help_text='Check to enable the feature')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductSafetyDataSheet',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('file_upload', wagtail.fields.StreamField([('file', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload a file', required=False))], blank=True, null=True, use_json_field=True)),
                ('is_file', models.BooleanField(default=False, help_text='Check to enable the feature')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DataSheetSecondMenu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('file_upload', wagtail.fields.StreamField([('file', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload a file', required=False))], blank=True, null=True, use_json_field=True)),
                ('is_file', models.BooleanField(default=False, help_text='Check to enable the feature')),
                ('category', modelcluster.fields.ParentalManyToManyField(blank=True, to='home.datasheetfirstmenu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='datasheetfirstmenu',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.productsafetydatasheet'),
        ),
    ]
